services:
  web:
    image: nginx:latest
    volumes:
      - ./app:/var/www/app
      - ./bootstrap:/var/www/bootstrap
      - ./routes:/var/www/routes
      - ./config:/var/www/config
      - ./resources:/var/www/resources
      - ./public:/var/www/public
      - ./database:/var/www/database
      - ./compose.dev.yaml:/var/www/compose.dev.yaml
      - ./compose.prod.yaml:/var/www/compose.prod.yaml
      - ./docker:/var/www/docker
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./package-lock.json:/var/www/package-lock.json
      - ./package.json:/var/www/package.json
      - ./vite.config.js:/var/www/vite.config.js
      - ./.env.example:/var/www/.env.example
      - ./.dockerignore:/var/www/.dockerignore
      - ./.editorconfig:/var/www/.editorconfig
      - ./artisan:/var/www/artisan
      - ./vendor:/var/www/vendor
      - app-node-modules:/var/www/node_modules
      - ./storage:/var/www/storage
      - ./docker/development/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
    networks:
      - laravel-development
    depends_on:
      php-fpm:
        condition: service_started

  php-fpm:
    image: laravel-php-fpm:dev
    build:
      context: .
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: development
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    pull_policy: never
    env_file:
      - .env
    user: "root"
    volumes:
      - ./app:/var/www/app
      - ./bootstrap:/var/www/bootstrap
      - ./routes:/var/www/routes
      - ./config:/var/www/config
      - ./resources:/var/www/resources
      - ./public:/var/www/public
      - ./database:/var/www/database
      - ./compose.dev.yaml:/var/www/compose.dev.yaml
      - ./compose.prod.yaml:/var/www/compose.prod.yaml
      - ./docker:/var/www/docker
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./package-lock.json:/var/www/package-lock.json
      - ./package.json:/var/www/package.json
      - ./vite.config.js:/var/www/vite.config.js
      - ./.env.example:/var/www/.env.example
      - ./.dockerignore:/var/www/.dockerignore
      - ./.editorconfig:/var/www/.editorconfig
      - ./artisan:/var/www/artisan
      - ./vendor:/var/www/vendor
      - app-node-modules:/var/www/node_modules
      - ./storage:/var/www/storage
    networks:
      - laravel-development
    depends_on:
      postgres:
        condition: service_started

  workspace:
    image: laravel-workspace:dev
    build:
      context: .
      dockerfile: ./docker/development/workspace/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    pull_policy: never
    ports:
      - '${VITE_PORT:-5173}:5173'
    tty: true
    stdin_open: true
    env_file:
      - .env
    volumes:
      - ./app:/var/www/app
      - ./bootstrap:/var/www/bootstrap
      - ./routes:/var/www/routes
      - ./config:/var/www/config
      - ./resources:/var/www/resources
      - ./public:/var/www/public
      - ./database:/var/www/database
      - ./compose.dev.yaml:/var/www/compose.dev.yaml
      - ./compose.prod.yaml:/var/www/compose.prod.yaml
      - ./docker:/var/www/docker
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./package-lock.json:/var/www/package-lock.json
      - ./package.json:/var/www/package.json
      - ./vite.config.js:/var/www/vite.config.js
      - ./.env.example:/var/www/.env.example
      - ./.dockerignore:/var/www/.dockerignore
      - ./.editorconfig:/var/www/.editorconfig
      - ./artisan:/var/www/artisan
      - ./vendor:/var/www/vendor
      - app-node-modules:/var/www/node_modules
      - ./storage:/var/www/storage
    networks:
      - laravel-development

  worker:
    image: laravel-workspace:dev
    build:
      context: .
      dockerfile: ./docker/development/workspace/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    pull_policy: never
    env_file:
      - .env
    command: php artisan queue:work --sleep=3 --tries=3
    restart: unless-stopped
    volumes:
      - ./app:/var/www/app
      - ./bootstrap:/var/www/bootstrap
      - ./routes:/var/www/routes
      - ./config:/var/www/config
      - ./resources:/var/www/resources
      - ./public:/var/www/public
      - ./database:/var/www/database
      - ./compose.dev.yaml:/var/www/compose.dev.yaml
      - ./compose.prod.yaml:/var/www/compose.prod.yaml
      - ./docker:/var/www/docker
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
      - ./package-lock.json:/var/www/package-lock.json
      - ./package.json:/var/www/package.json
      - ./vite.config.js:/var/www/vite.config.js
      - ./.env.example:/var/www/.env.example
      - ./.dockerignore:/var/www/.dockerignore
      - ./.editorconfig:/var/www/.editorconfig
      - ./artisan:/var/www/artisan
      - ./vendor:/var/www/vendor
      - app-node-modules:/var/www/node_modules
      - ./storage:/var/www/storage
    networks:
      - laravel-development
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started

  postgres:
    image: postgres:16
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-data-development:/var/lib/postgresql/data
    networks:
      - laravel-development

  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - laravel-development

  java-api:
    image: coooal/pcu-dasma-pe-project-java-api:main
    ports:
      - "8085:8090"
    networks:
      - laravel-development
    cap_drop: 
      - ALL
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 512m
          cpus: '0.50'
    stop_grace_period: 15s 
    stop_signal: SIGKILL 

  fastapi:
    image: coooal/pcu-dasma-pe-project-fastapi:main
    command: sh -c "ln -sf /code /code/app 2>/dev/null || true && uvicorn main:app --host 0.0.0.0 --port 80"
    working_dir: /code
    ports:
      - "8082:8080"
    depends_on:
      - redis
      - postgres
    networks:
      - laravel-development
    environment:
      - REDIS_HOST=redis
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}

networks:
  laravel-development:

volumes:
  postgres-data-development:
  app-node-modules:
  redis_dev_data:
